// <auto-generated />
using System;
using Identity.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Entities.nguoi_dung", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anh_dai_dien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("concurrency_stamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dang_nhap_that_bai")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gioi_tinh")
                        .HasColumnType("int");

                    b.Property<string>("ho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("khoa_dang_nhap")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("khoa_den_ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("mat_khau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("security_stamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("so_dien_thoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tai_khoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_day_du")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("nguoi_dung", "dbo");
                });

            modelBuilder.Entity("Identity.Domain.Entities.nguoi_dung_refresh_token", b =>
                {
                    b.Property<Guid>("nguoi_dung_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("da_thu_hoi")
                        .HasColumnType("bit");

                    b.Property<string>("ip_tao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ip_thu_hoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_het_han")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_thu_hoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thiet_bi_dang_nhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thiet_bi_dang_xuat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nguoi_dung_id");

                    b.ToTable("nguoi_dung_refresh_token", "dbo");
                });

            modelBuilder.Entity("Identity.Domain.Entities.nguoi_dung_refresh_token", b =>
                {
                    b.HasOne("Identity.Domain.Entities.nguoi_dung", "nguoi_dung")
                        .WithMany("lst_nguoi_dung_refresh_token")
                        .HasForeignKey("nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nguoi_dung");
                });

            modelBuilder.Entity("Identity.Domain.Entities.nguoi_dung", b =>
                {
                    b.Navigation("lst_nguoi_dung_refresh_token");
                });
#pragma warning restore 612, 618
        }
    }
}
